# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20, verbose_name='管理员用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'tb_admin_user',
            },
        ),
        migrations.CreateModel(
            name='AdminTicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ticket', models.CharField(max_length=256)),
                ('out_time', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.AdminModel')),
            ],
            options={
                'db_table': 'tb_admin_ticket',
            },
        ),
    ]
