# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('goods_pic', models.ImageField(upload_to='upload', verbose_name='商品图片')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('goods_specification', models.CharField(default='500g', max_length=20, verbose_name='商品规格')),
                ('goods_ID', models.CharField(max_length=20, verbose_name='商品编号')),
                ('goods_classify', models.CharField(max_length=20, verbose_name='商品分类')),
                ('goods_label', models.IntegerField(default=1, verbose_name='商品标签')),
            ],
        ),
    ]
