# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_name', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('recipients_address', models.CharField(max_length=100, verbose_name='收件人地址')),
                ('recipients_tel', models.CharField(max_length=40, verbose_name='收件人电话')),
                ('recipients_postcode', models.CharField(max_length=20, null=True, verbose_name='邮编号码')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'tb_recipient',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('tel', models.CharField(max_length=20, verbose_name='电话号码')),
                ('email', models.CharField(max_length=40, null=True, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='地址')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='UserTicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ticket', models.CharField(max_length=256)),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
            options={
                'db_table': 'tb_ticket',
            },
        ),
        migrations.AddField(
            model_name='recipientsmodel',
            name='userNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel'),
        ),
    ]
